from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pandas as pd

from src.pipeline_config import (
    FORMAL_BOUNDS_JSONL,
    FORMAL_BOUNDS_SUMMARY,
    LLM_PROMPTS_JSONL,
    MEETING_PACK_DIR,
    MEETING_SUMMARY_CSV,
    OLLAMA_RESPONSES_JSONL,
    REASONGUARD_REPORT_JSON,
    REASONGUARD_REPORT_JSONL,
    REASONGUARD_SUMMARY_CSV,
    SYNTHETIC_RESPONSES_JSONL,
    ensure_project_directories,
)


PIPELINE_STATS_PATH = MEETING_PACK_DIR / "pipeline_stats.md"


def load_json(path: Path) -> Any:
    with open(path, "r", encoding="utf-8") as file:
        return json.load(file)


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    records = []

    with open(path, "r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()

            if line:
                records.append(json.loads(line))

    return records


def per_model_counts(report_records: list[dict[str, Any]]) -> dict[str, dict[str, int]]:
    counts: dict[str, dict[str, int]] = {}

    for record in report_records:
        model_name = record.get("model_name") or "unknown"
        bucket = counts.setdefault(
            model_name,
            {"total": 0, "clean": 0, "V1": 0, "V2": 0, "V3": 0, "V4": 0, "V5": 0},
        )

        bucket["total"] += 1

        if not record.get("violation_codes"):
            bucket["clean"] += 1

        for code in record.get("violation_codes", []):
            if code in bucket:
                bucket[code] += 1

    return counts


def render_per_model_table(counts: dict[str, dict[str, int]]) -> str:
    if not counts:
        return "No per-model breakdown available."

    headers = ["model", "total", "clean", "V1", "V2", "V3", "V4", "V5"]
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("| " + " | ".join("---" for _ in headers) + " |")

    for model_name in sorted(counts):
        row = counts[model_name]
        lines.append(
            "| "
            + " | ".join(
                [
                    model_name,
                    str(row["total"]),
                    str(row["clean"]),
                    str(row["V1"]),
                    str(row["V2"]),
                    str(row["V3"]),
                    str(row["V4"]),
                    str(row["V5"]),
                ]
            )
            + " |"
        )

    return "\n".join(lines)


def collect_inputs() -> dict[str, Any]:
    inputs: dict[str, Any] = {
        "generated_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "have_bounds": FORMAL_BOUNDS_JSONL.exists(),
        "have_prompts": LLM_PROMPTS_JSONL.exists(),
        "have_synthetic": SYNTHETIC_RESPONSES_JSONL.exists(),
        "have_ollama": OLLAMA_RESPONSES_JSONL.exists(),
        "have_report": REASONGUARD_REPORT_JSON.exists(),
    }

    if inputs["have_bounds"]:
        inputs["bounds_count"] = sum(1 for _ in open(FORMAL_BOUNDS_JSONL, encoding="utf-8"))

    if inputs["have_prompts"]:
        inputs["prompts_count"] = sum(1 for _ in open(LLM_PROMPTS_JSONL, encoding="utf-8"))

    if inputs["have_synthetic"]:
        inputs["synthetic_count"] = sum(1 for _ in open(SYNTHETIC_RESPONSES_JSONL, encoding="utf-8"))

    if inputs["have_ollama"]:
        inputs["ollama_count"] = sum(1 for _ in open(OLLAMA_RESPONSES_JSONL, encoding="utf-8"))

    if FORMAL_BOUNDS_SUMMARY.exists():
        inputs["bounds_summary"] = load_json(FORMAL_BOUNDS_SUMMARY)

    if inputs["have_report"]:
        report = load_json(REASONGUARD_REPORT_JSON)
        inputs["summary"] = report.get("summary", {})

    if REASONGUARD_REPORT_JSONL.exists():
        report_records = load_jsonl(REASONGUARD_REPORT_JSONL)
        inputs["per_model"] = per_model_counts(report_records)

    return inputs


def render_pipeline_stats(inputs: dict[str, Any]) -> str:
    lines = [
        "# ReasonGuard Pipeline Stats",
        "",
        "*This file is auto-generated by `src/prepare_meeting_pack.py`. The curated*",
        "*weekly meeting pack lives in `week_NN_meeting_pack.md` and is hand-written.*",
        "",
        f"Generated at (UTC): {inputs['generated_at']}",
        "",
        "## Artefact counts",
        "",
    ]

    lines.append(f"- Formal bounds: {inputs.get('bounds_count', 'n/a')}")
    lines.append(f"- LLM prompts: {inputs.get('prompts_count', 'n/a')}")
    lines.append(f"- Synthetic responses: {inputs.get('synthetic_count', 'n/a')}")
    lines.append(f"- Real local-LLM responses (Ollama): {inputs.get('ollama_count', 'n/a')}")
    lines.append("")

    summary = inputs.get("summary", {})

    if summary:
        lines.append("## Violation summary")
        lines.append("")
        lines.append(f"- Total responses analysed: {summary.get('total_responses')}")
        lines.append(f"- No violation (clean): {summary.get('no_violation')}")
        lines.append(f"- V1 fabricated reasoning: {summary.get('V1_fabricated_reasoning')}")
        lines.append(f"- V2 contradicted reasoning: {summary.get('V2_contradicted_reasoning')}")
        lines.append(f"- V3 over-generalised reasoning: {summary.get('V3_over_generalised_reasoning')}")
        lines.append(f"- V4 under-specified reasoning: {summary.get('V4_under_specified_reasoning')}")
        lines.append(f"- V5 incoherent reasoning: {summary.get('V5_incoherent_reasoning')}")
        lines.append("")

    per_model = inputs.get("per_model")

    if per_model:
        lines.append("## Per-model breakdown")
        lines.append("")
        lines.append(render_per_model_table(per_model))
        lines.append("")

    bounds_summary = inputs.get("bounds_summary", {})
    proxy_event_counts = bounds_summary.get("proxy_event_type_counts")

    if proxy_event_counts:
        lines.append("## Proxy event-type distribution")
        lines.append("")

        for event_type, count in sorted(proxy_event_counts.items(), key=lambda pair: -pair[1]):
            lines.append(f"- {event_type}: {count}")

        lines.append("")

    return "\n".join(lines)


def copy_summary_csv() -> Path | None:
    if not REASONGUARD_SUMMARY_CSV.exists():
        return None

    df = pd.read_csv(REASONGUARD_SUMMARY_CSV)
    df.to_csv(MEETING_SUMMARY_CSV, index=False)

    return MEETING_SUMMARY_CSV


def main() -> None:
    ensure_project_directories()

    inputs = collect_inputs()
    stats_markdown = render_pipeline_stats(inputs)

    PIPELINE_STATS_PATH.write_text(stats_markdown, encoding="utf-8")
    csv_path = copy_summary_csv()

    print("Meeting pack stats refreshed successfully.")
    print(f"Pipeline stats: {PIPELINE_STATS_PATH}")

    if csv_path is not None:
        print(f"Meeting CSV: {csv_path}")
    else:
        print("Summary CSV not present yet; skipping copy.")


if __name__ == "__main__":
    main()
